export const SET_MVID = 'SET_MVID'

export const SET_PLAYMV = 'SET_PLAYMV'

export const SET_DISC = 'SET_DISC'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_SONG_HISTORY = 'SET_SONG_HISTORY'

export const SET_DISC_HISTORY = 'SET_DISC_HISTORY'

export const SET_FAVORITE_MV = 'SET_FAVORITE_MV' 

export const SET_FAVORITE_DISC = 'SET_FAVORITE_DISC'

export const SET_FAVORITE_SONG = 'SET_FAVORITE_SONG'

export const SET_DISC_SHOW = "SET_DISC_SHOW"

export const SET_QUERY = 'SET_QUERY'